[package]
name = "grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
colored = "2.1.0"
colorized = "1.0.0"
regex = "1.10.3"
walkdir = "2.4.0"
